name: Push protobuf updates to fabric-protos-go

on: 
  push: 
jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Push protobuf updates to fabric-protos-go
      env:
        DUMMY: ${{ secrets.dummy }}
        SECRET: $${{ secrets.secret }}
        DUMMY2: ${{ secrets.dummy }}
      run:  make update
