name: Push protobuf updates to fabric-protos-go

on: 
  push: 
jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Push protobuf updates to fabric-protos-go
      with:
        key: ${{ secrets.SSH_KEY }}
      run:  make update
