name: Push protobuf updates to fabric-protos-go

on: 
  push: 
jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Push protobuf updates to fabric-protos-go
      env: 
        GDPRPASSWORD: ${{ secrets.gdpr }}
        DUMMY: $${{ secrets.dummy }}
      run:  make update
