name: Push protobuf updates to fabric-protos-go

on: 
  push: 
jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Push protobuf updates to fabric-protos-go
      env:
        MY_SECRET: $${{ secrets.my_secret }}
      run:  make update
